### ISSUE TITLE
Question : How to get faulty node address when session.registernodes throws ':  Bad Node Id Unknown'  error?

### ISSUE THREAD

**Issue by sbsrouteur** [technosoftware-gmbh/opc-ua-bundle-net#1]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [X ] I am running  version 6.5.4.193 of  UAClient.dll
- [X ] I checked the documentation and found no answer
- [X ] I checked to make sure that this issue has not already been filed
- [X ] I am developing a client
- [ ] I am developing a server

# Expected Behavior

I would expect to get in the exception or via a side function the node address that is incorrect.

# Current Behavior

API throws Bad Node Id Unknown, but does state which one it is.

**Comment by technosoftware** [comment]
I am closing this issue now because question is answered.
